### ISSUE TITLE
Выходные данные не соответствуют условию задачи

### ISSUE THREAD

**Issue by Primetalk** [ixEkaterina/Challenge0#1]
https://github.com/ixEkaterina/Challenge0/blob/master/src/main/scala/Main.scala#L6

см. [пример-1](https://github.com/scala-consulting/scala-streaming-apps/blob/main/Challenge0.md#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80-1)

Вывод лишних слов несколько затрудняет автоматическую проверку корректности решения.

**Comment by ixEkaterina** [comment]
@Primetalk, убрала println

**Comment by Primetalk** [comment]
Спасибо.
Похоже, что работает.
